name: Build
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install choco packages
        run: choco install choco-packages.config -y

      - name: Add Winlibs to path
        run: echo "C:\ProgramData\chocolatey\lib\winlibs\tools\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check g++ version
        run: g++ --version

      - name: CMake configure
        run: cmake --preset debug

      - name: CMake build
        run: cmake --build --preset debug
